languageCode = "en-us"
baseUrl = "https://jenkawitzig.github.io/blog/"
title = "a tech.stuff blog"
theme = "PaperMod"
paginate = 10
disqusShortname = "jenka"
contentDir = "content"
#defaultExtension= "html"
#publishDir = "docs"
tags = [
  "apis",
  "architecture",
  "grpc",
]
features = [
  "analytics",
  "favicon",
  "multilingual",
  "pagination",
  "single-column",
  "syntax-highlighting"
]

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'Posts'
  pageRef = 'posts/'
  weight = 20
[[menu.main]]
  name = 'About'
  pageRef = 'about/'
  weight = 30


[Params]
#  avatarURL = "images/me.jpeg"
#  favicon_16 = "/Users/jenniferwitzig/blog/blog/images/me.jpeg"
  enableEmoji = true
  since = 2023
  author = "Jenka"
  description ="Coding girl with a strong passion for softwareT architecture and coding general"
  dateFormat = "2006-01-02"
  paginationSinglePost = true
#  style: auto
#  mainSections = [ "posts" ]
  readMore = true # show read more button
  readNextPosts = 5  # show 5 related posts, 0 by default
  disableSummary = true
  toc = true # display Table of Contents
  rssAsSocialIcon = true
  favorite = true
  colorScheme = "auto"
